name: Build Motorola Kernel
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Build Environment
        run: |
          sudo apt update
          sudo apt install -y bc build-essential zip gcc-aarch64-linux-gnu clang lld libssl-dev flex bison git

      - name: Configure BBR and Fix Moto Errors
        run: |
          TARGET_CONFIG="arch/arm64/configs/vendor/holi-qgki_defconfig"
          
          # تفعيل BBR و FQ
          echo "CONFIG_TCP_CONG_BBR=y" >> $TARGET_CONFIG
          echo "CONFIG_NET_SCH_FQ=y" >> $TARGET_CONFIG
          echo "CONFIG_DEFAULT_TCP_CONG=\"bbr\"" >> $TARGET_CONFIG
          
          # حل مشكلة "Moto DT w/o overlay is undefined"
          # سنقوم بتعريف خيارات الـ Overlay المطلوبة في الملف
          echo "CONFIG_BUILD_ARM64_DT_OVERLAY=y" >> $TARGET_CONFIG
          echo "CONFIG_MSM_DRM_TUI=y" >> $TARGET_CONFIG

      - name: Run Kernel Build
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          
          # تجهيز الإعدادات
          make O=out vendor/holi-qgki_defconfig
          
          # البدء بالبناء مع إضافة متغير تفعيل الـ DTBO لتجاوز خطأ الموتورولا
          make O=out CC=clang CROSS_COMPILE=aarch64-linux-gnu- HOSTCC=gcc CONFIG_BUILD_ARM64_DT_OVERLAY=y -j$(nproc)

      - name: Upload Result
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-Motorola-Final
          path: out/arch/arm64/boot/
